package com.example.podlingo.core

/**
 * Maps the past-tense and past-participle spellings of common irregular English verbs to their
 * base (dictionary headword) form - "gone"/"went" -> "go", "seen" -> "see", "took"/"taken" ->
 * "take". [EnglishStemmer] can't derive these: it only strips regular suffixes, but an irregular
 * verb's inflected forms don't share a stem with its base form at all, so no amount of suffix
 * stripping recovers "go" from "gone". Since the Oxford lists only contain base forms, an
 * irregular past tense/participle would otherwise miss every lookup and wrongly rank as the
 * hardest word in its sentence even though its base verb is elementary.
 *
 * This is a closed, stable set - English doesn't gain new irregular verbs - so it's hand-
 * maintained here rather than sourced from a bundled data file, matching [ElementaryFunctionWords].
 * Forms identical to their base spelling ("cut", "read", "put") are omitted: a literal Oxford
 * lookup already finds those directly, so a self-mapping entry would add nothing.
 */
object IrregularVerbForms {

    fun baseFormOf(word: String): String? = BASE_FORM_BY_INFLECTION[word]

    private val BASE_FORM_BY_INFLECTION: Map<String, String> = buildMap {
        fun verb(base: String, vararg inflections: String) {
            for (inflection in inflections) put(inflection, base)
        }

        verb("arise", "arose", "arisen")
        verb("awake", "awoke", "awoken")
        verb("bear", "bore", "born", "borne")
        verb("beat", "beaten")
        verb("become", "became")
        verb("begin", "began", "begun")
        verb("bend", "bent")
        verb("bet", "betted")
        verb("bind", "bound")
        verb("bite", "bit", "bitten")
        verb("bleed", "bled")
        verb("blow", "blew", "blown")
        verb("break", "broke", "broken")
        verb("breed", "bred")
        verb("bring", "brought")
        verb("build", "built")
        verb("burn", "burnt")
        verb("burst", "bursted")
        verb("buy", "bought")
        verb("catch", "caught")
        verb("choose", "chose", "chosen")
        verb("cling", "clung")
        verb("come", "came")
        verb("creep", "crept")
        verb("deal", "dealt")
        verb("dig", "dug")
        verb("dive", "dove")
        verb("draw", "drew", "drawn")
        verb("dream", "dreamt")
        verb("drink", "drank", "drunk")
        verb("drive", "drove", "driven")
        verb("eat", "ate", "eaten")
        verb("fall", "fell", "fallen")
        verb("feed", "fed")
        verb("feel", "felt")
        verb("fight", "fought")
        verb("find", "found")
        verb("flee", "fled")
        verb("fling", "flung")
        verb("fly", "flew", "flown")
        verb("forbid", "forbade", "forbidden")
        verb("forget", "forgot", "forgotten")
        verb("forgive", "forgave", "forgiven")
        verb("freeze", "froze", "frozen")
        verb("get", "got", "gotten")
        verb("give", "gave", "given")
        verb("go", "went", "gone")
        verb("grind", "ground")
        verb("grow", "grew", "grown")
        verb("hang", "hung")
        verb("hear", "heard")
        verb("hide", "hid", "hidden")
        verb("hold", "held")
        verb("keep", "kept")
        verb("kneel", "knelt")
        verb("know", "knew", "known")
        verb("lay", "laid")
        verb("lead", "led")
        verb("lean", "leant")
        verb("leap", "leapt")
        verb("learn", "learnt")
        verb("leave", "left")
        verb("lend", "lent")
        verb("lie", "lay", "lain")
        verb("light", "lit")
        verb("lose", "lost")
        verb("make", "made")
        verb("mean", "meant")
        verb("meet", "met")
        verb("mistake", "mistook", "mistaken")
        verb("mow", "mown")
        verb("overcome", "overcame")
        verb("pay", "paid")
        verb("prove", "proven")
        verb("ride", "rode", "ridden")
        verb("ring", "rang", "rung")
        verb("rise", "rose", "risen")
        verb("run", "ran")
        verb("saw", "sawn")
        verb("say", "said")
        verb("see", "saw", "seen")
        verb("seek", "sought")
        verb("sell", "sold")
        verb("send", "sent")
        verb("sew", "sewn")
        verb("shake", "shook", "shaken")
        verb("shine", "shone")
        verb("shoot", "shot")
        verb("show", "showed", "shown")
        verb("shrink", "shrank", "shrunk")
        verb("sing", "sang", "sung")
        verb("sink", "sank", "sunk")
        verb("sit", "sat")
        verb("sleep", "slept")
        verb("slide", "slid")
        verb("sling", "slung")
        verb("smell", "smelt")
        verb("sow", "sown")
        verb("speak", "spoke", "spoken")
        verb("speed", "sped")
        verb("spell", "spelt")
        verb("spend", "spent")
        verb("spill", "spilt")
        verb("spin", "spun")
        verb("spit", "spat")
        verb("spoil", "spoilt")
        verb("spring", "sprang", "sprung")
        verb("stand", "stood")
        verb("steal", "stole", "stolen")
        verb("stick", "stuck")
        verb("sting", "stung")
        verb("stink", "stank", "stunk")
        verb("strike", "struck")
        verb("strive", "strove", "striven")
        verb("swear", "swore", "sworn")
        verb("sweep", "swept")
        verb("swell", "swelled", "swollen")
        verb("swim", "swam", "swum")
        verb("swing", "swung")
        verb("take", "took", "taken")
        verb("teach", "taught")
        verb("tear", "tore", "torn")
        verb("tell", "told")
        verb("think", "thought")
        verb("throw", "threw", "thrown")
        verb("tread", "trod", "trodden")
        verb("understand", "understood")
        verb("undertake", "undertook", "undertaken")
        verb("wake", "woke", "woken")
        verb("wear", "wore", "worn")
        verb("weave", "wove", "woven")
        verb("weep", "wept")
        verb("win", "won")
        verb("wind", "wound")
        verb("withdraw", "withdrew", "withdrawn")
        verb("wring", "wrung")
        verb("write", "wrote", "written")
    }
}
